### ISSUE TITLE
Add Timeframe Filter

### ISSUE THREAD

**Issue by alxndr13** [inovex/CalendarSync#114]
In the TILpod Episode 37 (https://tilpod.net/episode/til037-story-telling-ueber-illegale-presenter) Dirk Deimeke & Sujeevan Vijayakumaran talked about calendaring systems and how they duplicate personal appointments manually in their work calendars, but mostly only if these appointments are during their defined worktimes. 

We could implement a filter so that Events outside of a specific timerange could be excluded.

**Comment by alxndr13** [comment]
Adressed this issue in #144

**Comment by MichaelEischer** [comment]
Fixed in #144
