### ISSUE TITLE
`KeepDescription` transformer drops all newlines and whitespace

### ISSUE THREAD

**Issue by lukasjarosch** [inovex/CalendarSync#176]
When using the `KeepDescription` transformer, I would've expected that the description is actually kept without
being modified.

Turns out all whitespace and crlf are stripped, see: https://github.com/inovex/CalendarSync/blob/main/internal/transformation/keepDescription.go#L21

I don't know whether there are differences in the adapters on how line-breaks are treated, so this might turn
out to be more painful than it looks. 
Otherwise, as long as the iCalendar spec allows it, the line-breaks could just be normalized.

**Comment by alxndr13** [comment]
should be fixed in #177

**Comment by frittentheke** [comment]
@alxndr13 I just tried your fix https://github.com/inovex/CalendarSync/pull/177 and it works great. Event descriptions now look WAY better. Thx for tackling a fix so quickly!

But I immediately observed an ever higher memory footprint for the first run:

`CalendarSync.service: Consumed 10.940s CPU time, 1.5G memory peak.`

but also for later runs without any changes to the source (or updates to the destination):

`CalendarSync.service: Consumed 3.885s CPU time, 954.7M memory peak.`


It was fluctuating around 300 to < 600MB with [the current 0.10.0 release](https://github.com/inovex/CalendarSync/releases/tag/v0.10.0).

```
Aug 08 15:12:47 : CalendarSync.service: Consumed 711ms CPU time, 301.4M memory peak.
Aug 09 07:55:08 : CalendarSync.service: Consumed 1.647s CPU time, 546.3M memory peak.
Aug 09 08:25:07 : CalendarSync.service: Consumed 594ms CPU time, 306.2M memory peak.
Aug 09 08:55:07 : CalendarSync.service: Consumed 795ms CPU time, 296.9M memory peak.
Aug 09 09:25:31 : CalendarSync.service: Consumed 758ms CPU time, 318.8M memory peak.
Aug 09 09:55:07 : CalendarSync.service: Consumed 698ms CPU time, 294.7M memory peak.
Aug 09 10:25:07 : CalendarSync.service: Consumed 612ms CPU time, 296.6M memory peak.
Aug 09 10:55:08 : CalendarSync.service: Consumed 1.822s CPU time, 540.2M memory peak.
Aug 09 11:25:08 : CalendarSync.service: Consumed 576ms CPU time, 294.1M memory peak.
Aug 09 11:55:07 : CalendarSync.service: Consumed 567ms CPU time, 294.4M memory peak.
Aug 09 12:25:07 : CalendarSync.service: Consumed 569ms CPU time, 294M memory peak.
Aug 09 12:55:08 : CalendarSync.service: Consumed 562ms CPU time, 296.6M memory peak.
Aug 09 13:25:08 : CalendarSync.service: Consumed 733ms CPU time, 294.2M memory peak.
Aug 09 13:55:08 : CalendarSync.service: Consumed 1.954s CPU time, 541.9M memory peak.
Aug 09 14:25:09 : CalendarSync.service: Consumed 788ms CPU time, 293.9M memory peak.
Aug 12 08:00:23 : CalendarSync.service: Consumed 3.388s CPU time, 552.4M memory peak.
```



P.S. @alxndr13  ... you might want to properly link your fix / PR to this issue (https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) :-)

**Comment by frittentheke** [comment]
> @frittentheke thanks for the infos, can you create a separate issue for that?

Done @alxndr13  - https://github.com/inovex/CalendarSync/issues/180
