### ISSUE TITLE
Do not sync events if the user declined an event invitation

### ISSUE THREAD

**Issue by alxndr13** [inovex/CalendarSync#45]
If a user declines an event invitation in his source calendar, the event still gets synced to the sink calendar. We should make it optional to sync these events.

**Comment by FlorianWilhelm** [comment]
Thanks! This would be an awesome feature :-)

**Comment by MichaelEischer** [comment]
> Instead of filtering in the adapters, we could simply add a new field to `models.Event`, populate it in the adapters and remove the event from the list of to be synced events in the synchronization process. (i actually find this the better option).

If we only ever use a `Declined` field to remove events, then directly removing the event would also be fine. I'm wondering whether a synced event in a sink calendar could end up as `declined`, in which case the event shouldn't be filtered out  automatically. It looks like the answer is no, at least for google calendars.

**Comment by alxndr13** [comment]
Worked on this in: #62

works for google and outlook, did not look into zep (we should consider deprecating this adapter as nobody uses it anyways 😂 )

**Comment by MichaelEischer** [comment]
#62 has been merged by now.
